### PR TITLE
Update profile-photo.jpg

### PR DESCRIPTION
**Pull request by Azmaeus**
I received a comment that the 2.1mb profile photo was much too large and definitely not web-optimized. I've processed it with Gimp reducing the ppi from 96 to 72, and exported at 60% quality (I tried 80% but it was 1.3mb), and reduced the chroma subsampling to 4:2:0. Now the profile photo is 689kb.

BEFORE:
image

AFTER:
image

### CODE REVIEW

**Comment by bobjohnbob** [comment]
Unless someone is going to try viewing this on a 8K tv, the largest you might need this to be is 864 pixels high  (40% height of a 4k screen) .  If you shrink the resolution down, you can probably get the size closer to 100k.

**Comment by Azmaeus** [comment]
> Unless someone is going to try viewing this on a 8K tv, the largest you might need this to be is 864 pixels high (40% height of a 4k screen) . If you shrink the resolution down, you can probably get the size closer to 100k.

Perfect, thanks! I appreciate the feedback. I should have just tried it; I asked ChatGPT and it didn't seem to think it would matter.

**Comment by Azmaeus** [comment]
I made the recommended adjustment to 917x864px and kept the other adjustments and now the photo is 98kb!

**Review by jesseolsen — APPROVED** [review]
Also, just FYI, you may want to look into WebP format -- they can be much smaller, which is great or mobile, which Google likes for SEO -- maybe SEO is not important for an about me, but good to keep in mind/habit

**Comment by Azmaeus** [comment]
Thanks @jesseolsen I suspected there was something better than jpeg! I made the switch to webp with the same adjustments mentioned above (except I didn't see an option to change the chroma subsampling) and the result is now 72kb. The photo is a little more smooth which is OK because it blends my skin a little and hides some blemishes :)

**Pull request merged**
